Repository gwastro/BBHX-waveform-model, pull requests merged in 2024-05, with the labels that each got.

#8 Add ci tests
  .github/workflows/tests.yml
  tests.py
Labels: enhancement, CI

#10 Fix CI
  .github/workflows/tests.yml
Labels: CI

#5 add TDI-2 support
  BBHX_PhenomD.py
  setup.py
  tests.py
Labels: enhancement

#11 Add lalsuite to mamba env
  .github/workflows/tests.yml
Labels: CI

#7 Add support for HoM
  BBHX_Phenom.py
  setup.py
  tests.py
Labels: enhancement

#14 use consistent approx name
  BBHX_Phenom.py
Labels: bug

#16 Add option to skip generator caching
  BBHX_Phenom.py
  tests.py
Labels: enhancement
